### ISSUE TITLE
problem with linkng the library

### ISSUE THREAD

**Issue by mohan-padmanabha** [Turbulence-Master/MeshGeneration-Framework#12]
Hello,
         I'm having an issue with linking the hdf5 libraries with with the program. I have to use the script which is provided by HDF5 group which links Fortran and HDF5 libraries but unable to generate module file.   
the path to the directory is  >> MeshGeneration-Framework/tree/master/src/mesh_formats/hdf5_io
bash file to install the library >>  MeshGeneration-Framework/src/mesh_formats/hdf5_io/install_hdf5.sh 
for compiling the code I have created a module >>    MeshGeneration-Framework/src/mesh_formats/hdf5_io/modulehdf5r.f90 
Thank you

**Comment by ilkaysolak** [comment]
#14
