### ISSUE TITLE
VTP sample file needed

### ISSUE THREAD

**Issue by viks4mech** [Turbulence-Master/MeshGeneration-Framework#13]
HI Ilkay,
As discussed please share a sample file and other details for the VTP  file type.
Thanks in advance.
Bipin

**Comment by ilkaysolak** [comment]
https://github.com/Turbulence-Master/MeshGeneration-Framework/commit/ca10160eec0e84bd7e28d0ffe2a110e95ea8aa74

I am not sure if it is useful.

**Comment by ilkaysolak** [comment]
are you looking to this examples? https://www.visitusers.org/index.php?title=ASCII_VTK_Files

**Comment by ilkaysolak** [comment]
[samples.zip](https://github.com/Turbulence-Master/MeshGeneration-Framework/files/1594825/samples.zip) new samples. Also see

**Comment by ilkaysolak** [comment]
Answered in #15
