### ISSUE TITLE
Documentation of the code

### ISSUE THREAD

**Issue by ilkaysolak** [Turbulence-Master/MeshGeneration-Framework#2]
Missing documentation. 

We need a system with doxygen or sphinx (or mix) for automatic documentation.

**Comment by aakash30jan** [comment]
Doxygen has been set up.

**Comment by ilkaysolak** [comment]
In this comment [09286cd4312e0cfc1c08332b3949852db01510d6](https://github.com/Turbulence-Master/MeshGeneration-Framework/commit/09286cd4312e0cfc1c08332b3949852db01510d6)? 

Is it accessible on ghpages(not necessary just asking)? or should I download?

**Comment by aakash30jan** [comment]
Hi

It's not accessible on GitHub Pages, you have to download to view. But
don't download it now, I have just set up the documentation generation with
Doxygen so when all the code is in its place(a few days before deadline), I
can easily generate LaTeX/HTML.
