### ISSUE TITLE
Issue with API for VTK

### ISSUE THREAD

**Issue by viks4mech** [Turbulence-Master/MeshGeneration-Framework#4]
This is a regarding an issue in VTK Fortran API (https://github.com/szaghi/VTKFortran). One of the dependencies of the VTK API, STIRINGIFOR has an issue and is not getting compiled. We have tried two of the methods mentioned in the README of the dependency, i.e with GNU MAKE and FOBIS and both of them gave an error with one of the two modules of this dependency with name stringifor_string_t.F90.

Link for the STRINGIFOR GITHUB repository:
https://github.com/szaghi/StringiFor

We have successfully compileed other third-party dependencies like PENF and BEFORE64. Once the above issue is resolved and STRINGIFOR is compiled, we will proceed to FOXY(the last dependencies).

Please guide us how to proceed, any suggestions are most welcome.

**Comment by ilkaysolak** [comment]
I do not see your updates in CMakeList.txt in the src directory in this repo. Where are they?

Probably, you will be able to bring all the sources into our project. And compile them within here. Manage the required links. 

Like:
https://github.com/szaghi/BeFoR64/tree/758c54e2be3168f5d7fd4d249c8d323f15b6b169/src/lib
https://github.com/szaghi/PENF/tree/cfafeeacc2dcef861f03fc9f7e287997df9aa139/src/lib
etc. etc.

Prepare those, we can have a look together.

**Comment by viks4mech** [comment]
Hi Ilkay,

I did that locally, attaching folder containing the SRC for all the Dependencies.
[COMPILEDFINAL.tar.gz](https://github.com/Turbulence-Master/MeshGeneration-Framework/files/1510579/COMPILEDFINAL.tar.gz)

**Comment by ilkaysolak** [comment]
Where is the Makefile, or CMakeList.txt ?

**Comment by viks4mech** [comment]
HI, i have attached the drive containing the make file that gives compilation error. please run the make file in the main folder.
looking forward to your comments
[VTKFortran-master.tar.gz](https://github.com/Turbulence-Master/MeshGeneration-Framework/files/1525320/VTKFortran-master.tar.gz)
.

**Comment by ilkaysolak** [comment]
Hi Bipin, I did not mean this. I believe this is the copy of the repo their (https://github.com/szaghi/VTKFortran). Is that correct?

I am wondering, how are you compiling? Not the makefile they have. They do have integrated stuff with  `Fobis` (https://github.com/szaghi/VTKFortran/wiki/Compile) but you may like to compile them by yourself. So you can write your own Makefile, or you can use `cmake` to generate necessary makefile(s). 

If this is getting too complicated you may leave the VTK format out of the list for the moment. '*.dat' files can serve well as a start. And `netcdf` format can be added easily with the subroutine I provided.

**Comment by ilkaysolak** [comment]
#15 connected.
