### ISSUE TITLE
Kind use

### ISSUE THREAD

**Issue by Dianafm15** [Turbulence-Master/MeshGeneration-Framework#5]
Good morning Ilkay,

I would like to know what is the difference between put i.e real(kind=8) and just real(8), I am checking but I cannot see any difference, can you explain me why people wants to use the kind.

Thank you for your time,

Best regards,
Diana F.

**Comment by ilkaysolak** [comment]
They are the same, real*8 is different.
https://stackoverflow.com/questions/3170239/fortran-integer4-vs-integer4-vs-integerkind-4?noredirect=1&lq=1
